### ISSUE TITLE
Minor typo in `cl-defun slot/vc-install`

### ISSUE THREAD

**Issue by alternateved** [slotThe/slotThe.github.io#1]
Hello!

Thanks for another great post on Emacs (https://tony-zorman.com/posts/2022-11-30-package-vc-install.html). I was eyeing that feature for quite some time, I am glad it was able to get into `emacs-29` branch.

I think I've found a minor typo in your function:

```lisp
(cl-defun slot/vc-install (&key (fetcher "github") repo name rev backend)
  "Install a package from a remote if it's not already installed.
This is a thin wrapper around `package-vc-install' in order to
make non-interactive usage more ergonomic.  Takes the following
named arguments:

- FETCHER the remote where to get the package (e.g., \"gitlab\").
  If omitted, this defaults to \"github\".

- REPO should be the name of the repository (e.g.,
  \"slotThe/arXiv-citation\".

- NAME, REV, and BACKEND are as in `package-vc-install' (which
  see)."
  (let* ((url (format "https://www.%s.com/%s" fetcher repo))
         (pac-name (intern (or name (file-name-base repo)))))
    (unless (package-installed-p pac-name)
      (package-vc-install url (intern name) rev backeng))))
```

In the last line there is `backeng` instead of `backend`. Most likely it did not come out as error for you since the function never visited that branch (packages were already installed).

Kind wishes,
alternateved

**Comment by slotThe** [comment]
Indeed, thanks for spotting that (and reading the post)!  

That function could've used some "proper" testing before publication :sweat_smile:.  I fixed this, as well as another mistake (`nil` _really_ doesn't like to be interned) in https://github.com/slotThe/slotThe.github.io/commit/c5ec60181cb8882e3820c70e7d20dc1a65593474
